[package]
name = "sculpt"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
syn = { version = "2.0.66", features = ["full", "extra-traits"] }
quote = "1.0.36"
proc-macro2 = "1.0.84"
rust-format = "0.3.4"
itertools = "0.13.0"